# Generated by Django 5.2.12 on 2026-04-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('payment_method', models.CharField(db_column='PAYMENT_METHOD', max_length=50)),
                ('transaction_id', models.CharField(db_column='TRANSACTION_ID', max_length=255, unique=True)),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, max_digits=10)),
                ('status', models.CharField(db_column='STATUS', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('booking', models.ForeignKey(db_column='BOOKING_ID', on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
            options={
                'db_table': 'PAYMENT_MT',
            },
        ),
    ]
