# Generated by Django 5.2.12 on 2026-04-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=100)),
                ('country', models.CharField(db_column='COUNTRY', max_length=100)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'CITY_MT',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('total_seats', models.IntegerField(db_column='TOTAL_SEATS')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'HALL_MT',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('row', models.CharField(db_column='ROW', max_length=5)),
                ('number', models.IntegerField(db_column='NUMBER')),
                ('seat_type', models.CharField(db_column='SEAT_TYPE', max_length=20)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('hall', models.ForeignKey(db_column='HALL_ID', on_delete=django.db.models.deletion.CASCADE, to='venues.hall')),
            ],
            options={
                'db_table': 'SEAT_MT',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255)),
                ('address', models.TextField(db_column='ADDRESS')),
                ('latitude', models.DecimalField(blank=True, db_column='LATITUDE', decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='LONGITUDE', decimal_places=6, max_digits=9, null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='CAPACITY', null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('city', models.ForeignKey(db_column='CITY_ID', on_delete=django.db.models.deletion.CASCADE, to='venues.city')),
            ],
            options={
                'db_table': 'VENUE_MT',
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='venue',
            field=models.ForeignKey(db_column='VENUE_ID', on_delete=django.db.models.deletion.CASCADE, to='venues.venue'),
        ),
    ]
