# Generated by Django 5.2.12 on 2026-04-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='tm_id',
            field=models.CharField(blank=True, db_column='TM_ID', max_length=100, null=True, unique=True),
        ),
    ]
