# Generated by Django 5.2.12 on 2026-04-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_tm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='tm_id',
        ),
    ]
