# Generated by Django 5.2.12 on 2026-05-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_remove_venue_tm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(db_column='NAME', db_index=True, max_length=255, unique=True),
        ),
    ]
