# Generated by Django 5.2.12 on 2026-05-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_alter_city_name_alter_city_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='venue',
            name='external_id',
            field=models.CharField(blank=True, db_column='EXTERNAL_ID', db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='source',
            field=models.CharField(blank=True, db_column='SOURCE', db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.TextField(blank=True, db_column='ADDRESS', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(db_column='CITY_ID', on_delete=django.db.models.deletion.PROTECT, to='venues.city'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(db_column='NAME', db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique_venue_per_city'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('external_id', 'source'), name='unique_external_source'),
        ),
    ]
