# Generated by Django 5.2.12 on 2026-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_alter_venue_unique_together_venue_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='venue',
            name='unique_external_source',
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['external_id', 'source'], name='VENUE_MT_EXTERNA_1ac665_idx'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), ('source__isnull', False)), fields=('external_id', 'source'), name='unique_external_source'),
        ),
    ]
