# Generated by Django 5.2.12 on 2026-05-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_remove_venue_unique_external_source_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name', 'city'], name='VENUE_MT_NAME_934233_idx'),
        ),
    ]
