# Generated by Django 5.2.12 on 2026-05-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_venue_venue_mt_name_934233_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.CharField(blank=True, db_column='COUNTRY_CODE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='country_name',
            field=models.CharField(db_column='COUNTRY_NAME', default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='state_code',
            field=models.CharField(blank=True, db_column='STATE_CODE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='state_name',
            field=models.CharField(blank=True, db_column='STATE_NAME', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
    ]
