# Generated by Django 5.2.12 on 2026-05-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_alter_city_unique_together_city_country_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state_code', 'country_code')},
        ),
    ]
