# Generated by Django 5.2.12 on 2026-04-30 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventmedia_unique_together'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLead',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('email', models.EmailField(db_column='EMAIL', max_length=254)),
                ('phone', models.CharField(db_column='PHONE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('event', models.ForeignKey(blank=True, db_column='EVENT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'db_table': 'EVENT_LEAD',
            },
        ),
    ]
