# Generated by Django 5.2.12 on 2026-04-10 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('slug', models.SlugField(db_column='SLUG', unique=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'CATEGORIES',
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('slug', models.SlugField(db_column='SLUG', unique=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'EVENT_TAG',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('seq_no', models.IntegerField(db_column='SEQ_NO')),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'LANGUAGE',
            },
        ),
        migrations.CreateModel(
            name='TicketMode',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=20, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('icon', models.CharField(blank=True, db_column='ICON', max_length=50)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
            ],
            options={
                'db_table': 'TICKET_MODE_MT',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('slug', models.SlugField(db_column='SLUG')),
                ('description', models.TextField(db_column='Description')),
                ('age_limit', models.IntegerField(blank=True, db_column='AGE_LIMIT', null=True)),
                ('release_date', models.DateTimeField(blank=True, db_column='RELEASE_DATE', null=True)),
                ('booking_start', models.DateTimeField(blank=True, db_column='BOOKING_START', null=True)),
                ('start_date', models.DateTimeField(db_column='START_DATE', db_index=True)),
                ('end_date', models.DateTimeField(db_column='END_DATE')),
                ('youtube_url', models.URLField(blank=True, db_column='YOUTUBE_URL', null=True)),
                ('terms_and_conditions', models.TextField(blank=True, db_column='TERMS')),
                ('refund_policy', models.TextField(blank=True, db_column='REFUND_POLICY')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('CANCELLED', 'CANCELLED'), ('ENDED', 'ENDED')], db_column='STATUS', max_length=20)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('category', models.ForeignKey(db_column='CATEGORIES_ID', on_delete=django.db.models.deletion.CASCADE, to='events.categories')),
                ('organizer', models.ForeignKey(db_column='ORGANIZER_ID', on_delete=django.db.models.deletion.CASCADE, to='organizer.organizer')),
                ('venue', models.ForeignKey(db_column='VENUE_ID', on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
                ('tags', models.ManyToManyField(blank=True, to='events.eventtag')),
                ('languages', models.ManyToManyField(blank=True, to='events.language')),
                ('ticket_modes', models.ManyToManyField(blank=True, to='events.ticketmode')),
            ],
            options={
                'db_table': 'EVENT_MT',
            },
        ),
        migrations.CreateModel(
            name='EventFAQ',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('seq_no', models.IntegerField(db_column='SEQ_NO')),
                ('question', models.CharField(db_column='QUESTION', max_length=255)),
                ('answer', models.TextField(db_column='ANSWER')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('event', models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'db_table': 'EVENT_FAQ_MT',
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('image', models.ImageField(db_column='IMAGE', upload_to='events/')),
                ('media_type', models.CharField(choices=[('banner', 'Banner'), ('gallery', 'Gallery'), ('thumbnail', 'Thumbnail')], db_column='MEDIA_TYPE', max_length=20)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('event', models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='event_media', to='events.event')),
            ],
            options={
                'db_table': 'EVENT_MEDIA',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('seq_no', models.IntegerField(db_column='SEQ_NO')),
                ('name', models.CharField(db_column='NAME', max_length=255)),
                ('bio', models.TextField(blank=True, db_column='BIO')),
                ('image', models.ImageField(db_column='IMAGE', upload_to='speakers/')),
                ('role', models.CharField(choices=[('ARTIST', 'Artist'), ('SPEAKER', 'Speaker')], db_column='ROLE', max_length=20)),
                ('performance_time', models.TimeField(blank=True, db_column='PERFORMANCE_TIME', null=True)),
                ('website', models.URLField(blank=True, db_column='WEBSITE')),
                ('instagram', models.URLField(blank=True, db_column='INSTAGRAM')),
                ('facebook', models.URLField(blank=True, db_column='FACEBOOK')),
                ('twitter', models.URLField(blank=True, db_column='TWITTER')),
                ('description', models.TextField(db_column='DESCRIPTION')),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=254, null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('event', models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'db_table': 'SPEAKER_MT',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255)),
                ('logo', models.ImageField(db_column='LOGO', upload_to='sponsors/')),
                ('website', models.URLField(blank=True, db_column='WEBSITE')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('event', models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'db_table': 'SPONSOR_MT',
            },
        ),
    ]
