# Generated by Django 5.2.12 on 2026-04-27 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='showtime',
            name='match_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='source_type',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='external_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showtime',
            name='hall',
            field=models.ForeignKey(blank=True, db_column='HALL_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.hall'),
        ),
    ]
