# Generated by Django 5.2.12 on 2026-04-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(db_column='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_column='TITLE', max_length=255),
        ),
    ]
