# Generated by Django 5.2.12 on 2026-04-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_description_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='tm_id',
            field=models.CharField(blank=True, db_column='TM_ID', help_text='Ticketmaster Segment/Genre ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='tm_param',
            field=models.CharField(db_column='TM_PARAM', default='segmentId', help_text='e.g., segmentId or genreId', max_length=50),
        ),
        migrations.AddField(
            model_name='eventtag',
            name='tm_keyword',
            field=models.CharField(blank=True, db_column='TM_KEYWORD', help_text='Keyword to search in Ticketmaster', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='tm_locale',
            field=models.CharField(blank=True, db_column='TM_LOCALE', help_text="e.g., 'en' or 'en-us'", max_length=10, null=True),
        ),
    ]
