# Generated by Django 5.2.12 on 2026-04-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_showtime_unique_together_showtime_match_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='image_url',
            field=models.URLField(blank=True, db_column='IMAGE_URL', null=True),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='image',
            field=models.ImageField(blank=True, db_column='IMAGE', null=True, upload_to='events/'),
        ),
    ]
