# Generated by Django 5.2.12 on 2026-04-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventmedia_image_url_alter_eventmedia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='layout_image_url',
            field=models.URLField(blank=True, db_column='LAYOUT_IMAGE_URL', null=True),
        ),
    ]
