# Generated by Django 5.2.12 on 2026-04-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_showtime_layout_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmedia',
            name='media_type',
            field=models.CharField(choices=[('BANNER', 'BANNER'), ('GALLERY', 'GALLERY'), ('THUMBNAIL', 'THUMBNAIL')], db_column='MEDIA_TYPE', max_length=20),
        ),
    ]
