# Generated by Django 5.2.12 on 2026-04-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventmedia_media_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmedia',
            unique_together={('event', 'image_url')},
        ),
    ]
