# Generated by Django 5.2.12 on 2026-04-30 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventmedia_unique_together'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='venue',
            field=models.ForeignKey(db_column='VENUE_ID', default=1, on_delete=django.db.models.deletion.CASCADE, to='venues.venue'),
            preserve_default=False,
        ),
    ]
