# Generated by Django 5.2.12 on 2026-05-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_showtime_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
