# Generated by Django 5.2.12 on 2026-05-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(db_column='SLUG', max_length=255),
        ),
    ]
