# Generated by Django 5.2.12 on 2026-05-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='seq_no',
        ),
    ]
