# Generated by Django 5.2.12 on 2026-05-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_language_seq_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tm_id',
            field=models.CharField(blank=True, db_column='TM_ID', help_text='Ticketmaster Segment/Genre ID', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_column='TITLE', max_length=255, unique=True),
        ),
    ]
