# Generated by Django 5.2.12 on 2026-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_category_tm_id_alter_event_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(db_column='SLUG'),
        ),
    ]
