# Generated by Django 5.2.12 on 2026-05-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tm_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tm_param',
        ),
        migrations.AddField(
            model_name='category',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
