# Generated by Django 5.2.12 on 2026-05-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_category_tm_id_remove_category_tm_param_and_more'),
        ('organizer', '0004_organizer_source_alter_organizer_external_id'),
        ('venues', '0008_venue_venue_mt_name_934233_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_external',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UPDATED_AT'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('CANCELLED', 'CANCELLED'), ('RESCHEDULED', 'RESCHEDULED'), ('SOLD_OUT', 'SOLD_OUT'), ('COMPLETED', 'COMPLETED')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='source_type',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL')], default='INTERNAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_column='TITLE', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['event', 'show_date'], name='SHOWTIME_MT_EVENT_I_d79294_idx'),
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['external_id', 'source'], name='SHOWTIME_MT_externa_af048e_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), ('source__isnull', False)), fields=('external_id', 'source'), name='unique_event_external_source'),
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), ('source__isnull', False)), fields=('external_id', 'source'), name='unique_showtime_external_source'),
        ),
    ]
