# Generated by Django 5.2.12 on 2026-04-10 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('show_date', models.DateField(blank=True, db_column='SHOW_DATE', null=True)),
                ('start_time', models.TimeField(blank=True, db_column='START_TIME', null=True)),
                ('end_time', models.TimeField(blank=True, db_column='END_TIME', null=True)),
                ('layout_image', models.ImageField(blank=True, db_column='LAYOUT_IMAGE', null=True, upload_to='venue_layouts/')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('event', models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('hall', models.ForeignKey(db_column='HALL_ID', on_delete=django.db.models.deletion.CASCADE, to='venues.hall')),
            ],
            options={
                'db_table': 'SHOWTIME_MT',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(db_column='TOTAL_AMOUNT', decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, db_column='PAYMENT_ID', max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, db_column='ORDER_ID', max_length=100, null=True)),
                ('qr_code', models.ImageField(blank=True, db_column='QR_CODE', null=True, upload_to='tickets/')),
                ('qr_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='LOCKED', max_length=20)),
                ('booking_time', models.DateTimeField(auto_now_add=True, db_column='BOOKING_TIME')),
                ('event', models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('showtime', models.ForeignKey(db_column='SHOWTIME_ID', on_delete=django.db.models.deletion.CASCADE, to='booking.showtime')),
            ],
            options={
                'db_table': 'BOOKING_MT',
            },
        ),
        migrations.CreateModel(
            name='TempBooking',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('expires_at', models.DateTimeField(db_column='EXPIRES_AT')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CONSUMED', 'Used')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('event', models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('showtime', models.ForeignKey(db_column='SHOWTIME_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.showtime')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TEMP_BOOKING',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ticket_code', models.CharField(db_column='TICKET_CODE', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('booking', models.ForeignKey(db_column='BOOKING_ID', on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('seat', models.ForeignKey(db_column='SEAT_ID', on_delete=django.db.models.deletion.CASCADE, to='venues.seat')),
            ],
            options={
                'db_table': 'TICKET_MT',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('price', models.DecimalField(db_column='PRICE', decimal_places=2, max_digits=10)),
                ('sold', models.IntegerField(db_column='SOLD', default=0)),
                ('locked', models.IntegerField(db_column='LOCKED', default=0)),
                ('color', models.CharField(blank=True, db_column='COLOR', max_length=20)),
                ('quantity', models.IntegerField(db_column='QUANTITY')),
                ('description', models.TextField(db_column='DESCRIPTION')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('show', models.ForeignKey(db_column='SHOW_ID', on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='booking.showtime')),
            ],
            options={
                'db_table': 'TICKET_TYPE_MT',
            },
        ),
        migrations.CreateModel(
            name='TempBookingItem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='QUANTITY')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('temp_booking', models.ForeignKey(db_column='TEMP_BOOKING_ID', on_delete=django.db.models.deletion.CASCADE, to='booking.tempbooking')),
                ('ticket_type', models.ForeignKey(db_column='TICKET_TYPE_ID', on_delete=django.db.models.deletion.CASCADE, to='booking.tickettype')),
            ],
            options={
                'db_table': 'TEMP_BOOKING_ITEM',
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='QUANTITY')),
                ('price', models.DecimalField(db_column='PRICE', decimal_places=2, max_digits=10)),
                ('ticket_id', models.CharField(db_column='TICKET_ID', max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('booking', models.ForeignKey(db_column='BOOKING_ID', on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('category', models.ForeignKey(db_column='CATEGORY_ID', on_delete=django.db.models.deletion.CASCADE, to='booking.tickettype')),
            ],
            options={
                'db_table': 'BOOKING_ITEM',
            },
        ),
    ]
