# Generated by Django 5.2.12 on 2026-04-11 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='category',
            field=models.ForeignKey(db_column='TICKET_TYPE_ID', on_delete=django.db.models.deletion.CASCADE, to='booking.tickettype'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='show',
            field=models.ForeignKey(db_column='SHOWTIME_ID', on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='booking.showtime'),
        ),
    ]
