# Generated by Django 5.2.12 on 2026-04-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookingitem_category_alter_tickettype_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='qr_token',
            field=models.CharField(blank=True, db_column='QR_TOKEN', max_length=64, null=True, unique=True),
        ),
    ]
