# Generated by Django 5.2.12 on 2026-04-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_used',
            field=models.BooleanField(db_column='IS_USED', default=False),
        ),
    ]
