# Generated by Django 5.2.12 on 2026-04-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_column='STATUS', default='LOCKED', max_length=20),
        ),
    ]
