# Generated by Django 5.2.12 on 2026-04-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=200)),
                ('email', models.EmailField(db_column='EMAIL', max_length=254)),
                ('phone', models.CharField(db_column='PHONE', max_length=20)),
                ('website', models.URLField(blank=True, db_column='WEBSITE')),
                ('instagram', models.URLField(blank=True, db_column='INSTAGRAM')),
                ('facebook', models.URLField(blank=True, db_column='FACEBOOK')),
                ('twitter', models.URLField(blank=True, db_column='TWITTER')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'ORGANIZER_MT',
            },
        ),
    ]
