# Generated by Django 5.2.12 on 2026-05-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(db_column='NAME', max_length=200, unique=True),
        ),
    ]
