# Generated by Django 5.2.12 on 2026-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_alter_organizer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='external_id',
            field=models.CharField(db_column='EXTERNAL_ID', db_index=True, default=1, help_text='Unique organizer ID from Ticketmaster', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizer',
            name='email',
            field=models.EmailField(blank=True, db_column='EMAIL', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(db_column='NAME', max_length=200),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='phone',
            field=models.CharField(blank=True, db_column='PHONE', max_length=20, null=True),
        ),
    ]
