# Generated by Django 5.2.12 on 2026-05-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_organizer_external_id_alter_organizer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='source',
            field=models.CharField(db_column='SOURCE', db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizer',
            name='external_id',
            field=models.CharField(db_column='EXTERNAL_ID', db_index=True, help_text='Unique organizer ID from Ticketmaster', max_length=100),
        ),
    ]
