# Generated by Django 5.2.12 on 2026-04-10 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('role_code', models.CharField(db_column='ROLE_CODE', max_length=50, unique=True)),
                ('role_name', models.CharField(db_column='ROLE_NAME', max_length=100)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'Role_MT',
            },
        ),
        migrations.CreateModel(
            name='Menubar',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('position', models.IntegerField(blank=True, db_column='POSITION', null=True)),
                ('menu_code', models.CharField(db_column='MENU_CODE', max_length=100, unique=True)),
                ('menu_name', models.CharField(db_column='MENU_NAME', max_length=100)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=150, null=True)),
                ('icon', models.CharField(blank=True, db_column='ICON', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('parent', models.ForeignKey(blank=True, db_column='PARENT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='access_control.menubar')),
            ],
            options={
                'db_table': 'Menubar_MT',
            },
        ),
        migrations.CreateModel(
            name='PermissionList',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('perm_code', models.CharField(db_column='PERM_CODE', max_length=45, unique=True)),
                ('perm_type', models.CharField(choices=[('BASE', 'BASE'), ('SPECIAL', 'SPECIAL')], db_column='PERM_TYPE', max_length=150)),
                ('perm_name', models.CharField(db_column='PERM_NAME', max_length=55)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('menu_code', models.ForeignKey(blank=True, db_column='MENU_CODE', null=True, on_delete=django.db.models.deletion.CASCADE, to='access_control.menubar', to_field='menu_code')),
            ],
            options={
                'db_table': 'PermissionList_MT',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('is_allowed', models.BooleanField(db_column='IS_ALLOWED', default=True)),
                ('menu_code', models.ForeignKey(db_column='MENU_CODE', on_delete=django.db.models.deletion.CASCADE, to='access_control.menubar', to_field='menu_code')),
                ('perm_code', models.ForeignKey(db_column='PERM_CODE', on_delete=django.db.models.deletion.CASCADE, to='access_control.permissionlist', to_field='perm_code')),
                ('role_code', models.ForeignKey(db_column='ROLE_CODE', on_delete=django.db.models.deletion.CASCADE, to='access_control.role', to_field='role_code')),
            ],
            options={
                'db_table': 'RolePermission_MT',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('role_code', models.ForeignKey(db_column='ROLE_CODE', on_delete=django.db.models.deletion.CASCADE, to='access_control.role', to_field='role_code')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserRole_MT',
            },
        ),
    ]
