# Generated by Django 5.2.12 on 2026-04-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menubar',
            table='MENUBAR_MT',
        ),
    ]
