# Generated by Django 5.2.12 on 2026-05-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menubar',
            name='section',
            field=models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY')], db_column='SECTION', default='PRIMARY', max_length=20),
        ),
    ]
